# AUTOGENERATED! DO NOT EDIT! File to edit: ../main.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'examples', 'intf', 'is_cat', 'classify']

# %% ../main.ipynb 3
from fastai.vision.all import *
import gradio as gr

def is_cat(x): return x[0].isupper()

# %% ../main.ipynb 8
learn = load_learner('model.pkl')

# %% ../main.ipynb 9
categories = ('Dog', 'Cat')

def classify(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% ../main.ipynb 11
image = gr.inputs.Image(shape=(192, 192))
label - gr.outputs.Label()
examples = ['dog.jpg', 'cat.jpg']

intf = gr.Interface(fn=classify_image, inputs=image, outputs=labels, examples=examples)
intf.launch(inline=False)
